server:
  port: 8080

spring:
  application:
    name: pr-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
    properties:
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000

kafka:
  topics:
    feature-updates: FeatureUpdatesQueue


logging:
  level:
    nz.co.eroad.qaisystem: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
